# Input table
genomes_file: tests/data/genome_download_n10.tsv

# Output directory
output_dir: tests/output_n10/

# Temporary output directory (/dev/shm/ for shared memory)
tmp_dir: /tmp/

# Email for notifications ("Skip" to skip)
email: Skip

# software parameters
## Use "Skip" to skip  steps. If no params for rule, use ""
## `reps:` is the number of replicate simulations
## If `keep_reads: True`, then simulated reads are kept
params:
  # simulating metagenomes
  reps: 2
  MGSIM:
    genome_download: ""
    community_richness:
      - 1
    reads: --art-paired --art-mflen 250 --art-sdev 10
    read_depth:
      - 1000000
  keep_reads: True #False
  # coverage
  nonpareil: -T kmer
  nonpareil_summary: 1e9   # this is target seq. depth
  # assemblying metagenomes
  assemblers:
    metaspades: -k auto --only-assembler
    megahit: --min-count 3 --min-contig-len 1000 --presets meta-sensitive
  # assembly filtering
  contig_length_cutoff: 1000       # length in bp 
  # assessing assembly errors
  minimap2: ""
  metaquast: --min-identity 95 --extensive-mis-size 100 --no-icarus --max-ref-number 0
  # mapping reads to contigs  
  samtools: ""
  keep_bam: True
  # creating DL features
  make_features: --window 4
  # state-of-the-art
  ## ALE
  ALE: ""
  ## VALET
  VALET: ""
  
# snakemake pipeline
pipeline:
  snakemake_folder: ./
  script_folder: ./bin/scripts/
  rnd_seed: 9384