channels:
- conda-forge
- bioconda
dependencies:
- python>=3.6
- mamba>=0.11
- tensorflow
- tensorboard
- keras
- scikit
- learn
- ipython
- pytest
- gcc_linux-64>=8
- gxx_linux-64>=8
- cmake>=3.13
- pandas>=1.1.2
- snakemake>=5.31.1
