channels:
- conda-forge
- bioconda
dependencies:
- pip
- cmake>=3.13
- cython
- ipython
- keras
- mamba>=0.11
- pandas
- pathos
- pytables
- pytest
- pytest-console-scripts
- python>=3.9
- pandas>=1.1.2
- scikit-learn
- snakemake>=5.31.1
- tensorflow
- tensorboard
- toolz
