channels:
- conda-forge
- bioconda
dependencies:
- cmake>=3.13
- ipython
- keras
- mamba>=0.11
- pytables
- pytest
- python>=3.6
- pandas>=1.1.2
- scikit-learn
- snakemake>=5.31.1
- tensorflow
- tensorboard
- toolz
