channels:
- conda-forge
- bioconda
dependencies:
- pip
- cmake>=3.13
- cython
- ipython
- keras
- pandas
- pathos
- pytables
- pandas>=1.1.2
- scikit-learn
- snakemake>=5.31.1
- tensorflow
- tensorboard
- toolz
- samtools
- pysam
- pytest
- pytest-console-scripts
