# Input table
## Table of genomes
genomes_file: genomes_n10/genomes.tsv

# Output directory
output_dir: tests/output/n10/

# Temporary output directory (use /dev/shm/ for shared memory)
tmp_dir: resmico-sm_TMP/

# Email for notifications ("Skip" to skip)
email: Skip

# software parameters for data simulations
## Use "Skip" to skip  steps. If no params for rule, use ""
## `reps:` is the number of replicate simulations
## If `keep_reads: True`, then simulated reads are kept
params:
  ionice: -c 3
  # simulating metagenomes
  MGSIM:
    sim_reps: 1
    community:
      richness:
        - 0.5
        - 0.8
      abundance_distribution:
        - "mean:10,sigma:1"
        - "mean:10,sigma:2"
      random_seed: Skip #8192
      other_sim_params: --group-bias 0
    reads: 
      length:
        - 100
        - 150
      depth:
        - 1000000
        - 4000000
      other_sim_params: --art-paired --art-mflen 270 --art-sdev 50 --rndSeed 8712
                        --art-qprof1 data/art_error_profiles/HiSeq2500L150R1.txt
                        --art-qprof2 data/art_error_profiles/HiSeq2500L150R2.txt
      skewer: -n -l 70 -q 25 --format sanger
      keep_reads: False
  # coverage
  nonpareil:
    params: -T kmer
    summary: 1e9   # this is target seq. depth
  # assemblying metagenomes
  assemblers:
    metaspades: -k auto --only-assembler
    megahit: --min-count 1 --min-contig-len 1000
  # assembly filtering
  contigs:
    length_cutoff: 1000       # length in bp 
  # assessing assembly errors
  asmbl_errors:
    metaquast: --max-ref-number 0 --min-contig 1000 --min-identity 95 --extensive-mis-size 100
               --no-html --no-plots --no-icarus --no-gc --no-snps --no-sv
    keep_genomes: False
  # mapping reads to contigs
  map:
    contig_frac:
      - 1000
      - 1500
    samtools: ""
    bowtie2: ""
    max_coverage: 20
    keep_bam: False
    keep_faidx: False
    create_bigwig: False
  # creating ResMiCo feature tables
  feature_table:
    make: --window 6
  # state-of-the-art
  SotA:
    ALE: ""
    VALET: ""
    metaMIC:
      extract: --mlen 1000
      predict: --mlen 1000 --slen 500 -a MEGAHIT
  # misc
  real_contigs_simulated_reads: False

# params just for creating feature tables for non-simulated data
nonsim_params:
  # max number of reads to use
  subsample_reads: Skip #1000000

# snakemake pipeline
pipeline:
  snakemake_folder: ./
  script_folder: ./bin/scripts/
  name: ResMiCo-SM
