name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse       
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Artifact download
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish package to PyPI
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
