name: ResMiCo

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    env:
      DATADIR: data
    strategy:
      matrix:
        python-version: [3.6]
        build_type: [Release]
        compiler: [g++-9]
        include:
          - compiler: g++-9
            cxx: g++-9
            cc: gcc-9
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: bam2feat Create build dir
      run: mkdir ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
    - name: bam2feat Configure CMake
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: |
        export CC=$(which ${{ matrix.cc }})
        export CXX=$(which ${{ matrix.cxx }})
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: bam2feat Build
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: make -j
    - name: bam2feat Test
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: ./tests
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: resmico
    - name: conda env setup
      shell: bash -l {0}
      run: |
        conda info -a
        conda env update -f conda_env.yaml python=${{ matrix.python-version }}
        conda list
        conda activate /usr/share/miniconda3/envs/resmico
    - name: cython contig reader
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/resmico
      run: |
          python setup.py build_ext --inplace
    - name: test_resmico
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/resmico/tests
      run: |
        pytest ./test_models_fl.py ./test_contig_reader.py ./test_train.py
#    - name: pytest
#      shell: bash -l {0}
#      run: |
#        pytest -s --ignore ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor
#    - name: snakemake
#      shell: bash -l {0}
#      run: |
#        snakemake --directory ResMiCo-SM --snakefile ResMiCo-SM/Snakefile -F --dryrun
